"""Plain short forms (owner, 2026-10-07): each short form is the initials of its full name, in capitals, no subscripts.
id -> (full name, short form)."""
NAMES = {
    # stage 1
    "vr": ("Visit Rate", "VR"), "v": ("Page Visits", "PV"),
    "vr_e": ("Visit Rate, Cold Email", "VRCE"), "vr_c": ("Visit Rate, Calendar Invites", "VRCI"), "vr_l": ("Visit Rate, LinkedIn", "VRL"),
    "vr_a": ("Visit Rate, Ads", "VRA"), "vr_o": ("Visit Rate, Posts", "VRP"),
    "n_e": ("People Emailed", "PE"), "n_c": ("Calendar Invites Sent", "CIS"), "n_l": ("LinkedIn Requests Sent", "LRS"), "n_a": ("Ad Impressions", "AI"), "n_o": ("Post Impressions", "PI"),
    "dr_e": ("Email Delivery Rate", "EDR"), "or_e": ("Email Open Rate", "EOR"), "cr_e": ("Email Link Click Rate", "ELCR"), "lr": ("Page Load Rate", "PLR"),
    "dr_c": ("Invite Delivery Rate", "IDR"), "cl_c": ("Invite Click Rate", "ICR"),
    "ac_l": ("LinkedIn Acceptance Rate", "LAR"), "ms_l": ("LinkedIn Message Rate", "LMR"), "cr_l": ("LinkedIn Click Rate", "LCR"),
    "ct_a": ("Ad Click-Through Rate", "ACTR"), "lv_a": ("Ad Page View Rate", "APVR"), "ct_o": ("Post Link Click Rate", "PLCR"),
    # stage 2
    "pa": ("Page-to-Attendee Rate", "PAR"), "hw": ("Half-Watch Rate", "HWR"), "pq": ("Page-to-Day-and-a-Half Rate", "PDHR"),
    "rr": ("Registration Rate", "RR"), "st": ("Page Stay Rate", "PSR"), "fs": ("Form View Rate", "FVR"), "ft": ("Form Start Rate", "FSR"),
    "fc": ("Form Completion Rate", "FCR"), "su_f": ("Page Sign-Up Show Rate", "PSSR"), "su_0": ("No-Action Show Rate", "NASR"),
    "su_1": ("Action Show Rate", "ASR"), "t1": ("Thank You Action Rate", "TAR"),
    "ar": ("Auto-Registrants", "AR"), "ar_c": ("Calendar Sign-Ups", "CSU"), "ar_e": ("Email Sign-Ups", "ESU"), "ar_l": ("LinkedIn Sign-Ups", "LSU"),
    "ar_o": ("Inbound Sign-Ups", "ISU"), "ys": ("Yes Rate", "YR"), "my": ("Maybe Rate", "MR"), "rp_e": ("Email Reply Rate", "ERR"),
    "ye": ("Email Interested Share", "EIS"), "rp_l": ("LinkedIn Reply Rate", "LRR"), "yl": ("LinkedIn Interested Share", "LIS"),
    "eg": ("Post Engagement Rate", "PER"), "mg": ("Inbound Message Rate", "IMR"), "ir": ("Inbound Registration Rate", "IRR"), "r": ("Registrants", "R"),
    "pl": ("Video Play Rate", "VPR"), "hh": ("Halfway Rate", "HR"), "h_1": ("First-Visit Half-Watchers", "FVHW"),
    "os": ("Early Exit Opt-In Rate", "EEOR"), "p": ("Remindable People", "RP"),
    # stage 3
    "su": ("Show-Up Rate", "SUR"), "nh": ("Nurtured Half-Watch Rate", "NHWR"), "qd": ("Day-and-a-Half Rate", "DHR"), "su_d": ("Day 1 Show-Up Rate", "D1SR"),
    "dj": ("Direct Join Rate", "DJR"), "j_e": ("Email Joins", "EJ"), "j_w": ("WhatsApp Joins", "WJ"), "j_s": ("SMS Joins", "SJ"), "j_v": ("Call Joins", "CJ"),
    "dr_m": ("Reminder Email Delivery Rate", "REDR"), "or_m": ("Reminder Email Open Rate", "REOR"), "jc_m": ("Email Join Click Rate", "EJCR"),
    "wo": ("WhatsApp Opt-In Rate", "WOR"), "dr_w": ("WhatsApp Delivery Rate", "WDR"), "rd_w": ("WhatsApp Read Rate", "WRR"),
    "jc_w": ("WhatsApp Join Click Rate", "WJCR"), "sr_s": ("SMS Reach Rate", "SRR"), "dr_s": ("SMS Delivery Rate", "SDR"), "jc_s": ("SMS Join Click Rate", "SJCR"),
    "ph": ("Phone Share", "PS"), "an": ("Call Answer Rate", "CAR"), "cf": ("Call Confirm Rate", "CCR"), "cc": ("Came After Confirming Rate", "CACR"),
    "a": ("Attendees", "A"), "bb_e": ("Email Comebacks", "EC"), "bb_w": ("WhatsApp Comebacks", "WC"), "bb_s": ("SMS Comebacks", "SC"), "bb_v": ("Call Comebacks", "CC"),
    "bc_e": ("Email Comeback Click Rate", "ECCR"), "bc_w": ("WhatsApp Comeback Click Rate", "WCCR"), "bc_s": ("SMS Comeback Click Rate", "SCCR"),
    "bc_v": ("Post-Call Comeback Rate", "PCCR"), "hr": ("Return Halfway Rate", "RHR"), "h": ("Total Half-Watchers", "THW"), "sk": ("Series Stick Rate", "SSR"),
    "d_1": ("Day 1 Attendees", "D1A"), "d_2": ("Day 2 Attendees", "D2A"), "d_3": ("Day 3 Attendees", "D3A"),
    "ret_2": ("Day 2 Return Rate", "D2RR"), "ret_3": ("Day 3 Return Rate", "D3RR"), "q": ("Day-and-a-Half Attendees", "DHA"),
    # stage 4
    "br": ("Booking Rate", "BR"), "br_h": ("Booking Rate", "BR"), "bq": ("Booking Rate", "BR"),
    "so": ("Offer Stay Rate", "OSR"), "en": ("Engaged Share", "ES"), "ce": ("Engaged Offer Click Rate", "EOCR"), "cq": ("Quiet Offer Click Rate", "QOCR"),
    "ct": ("Offer Click-Through Rate", "OCTR"), "bf": ("Booking Completion Rate", "BCR"), "bl": ("Live Booking Rate", "LBR"), "fu": ("Follow-Up Click Rate", "FUCR"),
    "ns": ("No-Shows per Attendee", "NSA"), "rw": ("Replay Watch Rate", "RWR"), "rc": ("Replay Click Rate", "RCR"), "b": ("Calls Booked", "CB"),
    "rt": ("Button Reach Rate", "BRR"), "ap": ("Apply Click Rate", "ACR"), "af": ("Application Finish Rate", "AFR"), "ab": ("Application Booking Rate", "ABR"),
    "b_1": ("Day 1 Booking Rate", "D1BR"), "b_2": ("Day 2 Booking Rate", "D2BR"), "b_3": ("Day 3 Booking Rate", "D3BR"),
    "bd": ("Live Bookings", "LB"), "fb": ("Follow-Up Bookings", "FUB"),
    # stage 5
    "cl": ("Close Rate", "CR"), "sh": ("Call Show Rate", "CSR"), "sh_0": ("Unprompted Show Rate", "USR"),
    "sh_e": ("Email Confirmed Shows", "ECS"), "sh_w": ("WhatsApp Confirmed Shows", "WCS"), "sh_s": ("SMS Confirmed Shows", "SCS"), "sh_v": ("Call Confirmed Shows", "CCS"),
    "dr_r": ("Call Reminder Delivery Rate", "CRDR"), "or_r": ("Call Reminder Open Rate", "CROR"),
    "cs_e": ("Email Show Confirm Rate", "ESCR"), "cs_w": ("WhatsApp Show Confirm Rate", "WSCR"), "cs_s": ("SMS Show Confirm Rate", "SSCR"), "cs_v": ("Call Show Confirm Rate", "CSCR"),
    "wp": ("Booked WhatsApp Reach", "BWR"), "sp": ("Booked SMS Reach", "BSR"), "pv": ("Booked Phone Share", "BPS"), "av": ("Reminder Call Answer Rate", "RCAR"),
    "rb": ("Rebook Rate", "RBR"), "f_1": ("No-Show Follow-Up 1 Rate", "NF1R"), "f_2": ("No-Show Follow-Up 2 Rate", "NF2R"), "f_3": ("No-Show Follow-Up 3 Rate", "NF3R"),
    "f_4": ("No-Show Follow-Up 4 Rate", "NF4R"), "f_5": ("No-Show Follow-Up 5 Rate", "NF5R"), "hd": ("Calls Held Rate", "CHR"),
    "qr": ("Qualified Rate", "QR"), "pr": ("Proposal Rate", "PR"), "wn": ("Win Rate", "WR"), "w_0": ("Win Without Chasing", "WWC"),
    "d_1f": ("Deal Follow-Up 1 Rate", "DF1R"), "d_2f": ("Deal Follow-Up 2 Rate", "DF2R"), "d_3f": ("Deal Follow-Up 3 Rate", "DF3R"),
    "py": ("Payment Completion Rate", "PCR"), "ob": ("Onboarding Completion Rate", "OCR"), "c": ("Onboarded Customers", "OC"),
    # stage 6
    "yb": ("Yearly Rebooking Rate", "YRR"), "l": ("List Size", "LS"),
    "y_n": ("Weekly Email Bookings", "WEB"), "rc_n": ("Weekly Email Reach", "WER"), "sn_n": ("Weekly Email Sends", "WES"), "dl_n": ("Weekly Email Delivery Rate", "WEDR"),
    "op_n": ("Weekly Email Open Rate", "WEOR"), "ck_n": ("Weekly Email Click Rate", "WECR"),
    "y_i": ("AI Newsletter Bookings", "ANB"), "rc_i": ("AI Newsletter Reach", "ANR"), "sn_i": ("AI Newsletter Sends", "ANS"), "dl_i": ("AI Newsletter Delivery Rate", "ANDR"),
    "op_i": ("AI Newsletter Open Rate", "ANOR"), "ck_i": ("AI Newsletter Click Rate", "ANCR"),
    "y_w": ("Nurture WhatsApp Bookings", "NWB"), "rc_w": ("Nurture WhatsApp Reach", "NWR"), "sn_w": ("Nurture WhatsApp Sends", "NWS"), "dl_w": ("Nurture WhatsApp Delivery Rate", "NWDR"),
    "op_w": ("Nurture WhatsApp Read Rate", "NWRR"), "ck_w": ("Nurture WhatsApp Click Rate", "NWCR"),
    "y_s": ("Nurture SMS Bookings", "NSB"), "rc_s": ("Nurture SMS Reach", "NSR"), "sn_s": ("Nurture SMS Sends", "NSS"), "dl_s": ("Nurture SMS Delivery Rate", "NSDR"),
    "ck_s": ("Nurture SMS Click Rate", "NSCR"),
    "y_v": ("Check-In Call Bookings", "CICB"), "rc_v": ("Check-In Call Reach", "CICR"), "sn_v": ("Check-In Calls", "CIC"), "an_v": ("Check-In Answer Rate", "CIAR"),
    "bv": ("Check-In Booking Rate", "CIBR"), "bk": ("Click-to-Booking Rate", "CBR"), "b_y": ("Yearly Calls Booked", "YCB"), "c_y": ("Yearly Customers", "YC"),
}
